### PR TITLE
Review the results once more

### PR DESCRIPTION
**Pull request by leouieda**
Making small touches to the text to make sure we don't miss anything.

### CODE REVIEW

**Comment by leouieda** [comment]
Has the commits from #161 for now. Will rebase once that is merged.

**Comment by leouieda** [comment]
@santisoler finished the results but couldn't get to the discussion in time, sorry.

I made some tweaks to the figures and the text but again nothing major. Feel free to make any changes you see fit and merge when ready!

I'll finish this off as soon as I get back from vacation (or sooner if I get bored 🙂).

**Comment by santisoler** [comment]
> @santisoler finished the results but couldn't get to the discussion in time, sorry.

Thanks! Don't worry for the discussion, we can do that later.

> I made some tweaks to the figures and the text but again nothing major. Feel free to make any changes you see fit and merge when ready!

:+1:

> I'll finish revising as soon as I get back from vacation (or sooner if I get bored slightly_smiling_face).

I forbid you. I won't merge any PR you make until you come back from the vacations. And I'll be watching commit datetimes on any PR you open later on :eyes:

**Review by santisoler — COMMENTED** [review]
I think the changes are very nice. What I would revert is the change of color in the synthetics. I liked to use viridis in the target grid and in the synthetic datsets for two reasons:

1. The synthetic datasets are not very symmetric around zero.
2. Using viridis makes easier to visually understand whether we are plotting the synthetic data or any kind of residuals.

What do you think?

**Comment by leouieda** [comment]
TODO:

- [ ] Change back to viridis
- [ ] Crop colorbar in random vs sequential figure

**Comment by leouieda** [comment]
@santisoler I reverted the cmap back to viridis, made the cmap of the random vs sequential figure the same as the difference figures, and made the Australia CV figure into a single column instead of full width. See what you think and if you're happy, then please merge away. I'll look at the discussion in another PR.

**Comment by santisoler** [comment]
Awesome! I'm merging this! Thanks a lot!

**Pull request merged**
