### PR TITLE
Add vPICO slide for EGU21

### PR DESCRIPTION
**Pull request by santisoler**
Add abstract for EGU21 with doi to the EGU website.
Add slide for the 2mins vPICO talk in svg, PDF and png formats.
Add information to `presentations/egu21/README.md` file.

### CODE REVIEW

**Comment by santisoler** [comment]
@leouieda Would you take a look at the slide? I think I made all the changes we talked about, but if you see any spot of improvement, please ping me!

**Comment by leouieda** [comment]
@santisoler could you post a png? I’m having trouble with the svg on the website

**Comment by santisoler** [comment]
> @santisoler could you post a png? I’m having trouble with the svg on the website

I just pushed a PDF version, does it works for you?

**Comment by santisoler** [comment]
Sorry, the push failed because I had to pull before 🤦🏼

**Comment by leouieda** [comment]
Thanks, that works now. Looks really good, as always! A few suggestions:

1. A bit more space between text and source/data plots
2. Maybe colour the step size in purple as well to reinforce the connection to that step
3. Number the steps. I keep wanting to go from “select and fit in window 1” to “calculate residuals” instead of “find step size”. Having numbers would help with that.

**Comment by santisoler** [comment]
Thanks @leouieda for all the tips. I'm merging this and uploading it to EGU21 and figshare. If you find any mistake, please let me know before tomorrow at 15:30 CEST.

**Pull request merged**
